### ISSUE TITLE
Enabling mesos breaks config file

### ISSUE THREAD

**Issue by dalsh** [deric/dcos-traefik#1]
When I enable Mesos in the configuration, I get the following error :

```
Error reading TOML config file /var/lib/mesos/slave/slaves/68c8b26c-783c-4313-920a-177cefde7201-S1/frameworks/85135f6c-1848-4310-b185-0d936eea4674-0001/executors/traefik.7a85b8f0-932f-11e8-9d6f-36ef774772fc/runs/0fd8c9cd-1e83-493d-9a8a-20ce60b2cffb/traefik.toml : toml: cannot load TOML value of type string into a Go integer
```

I changed all timeout values to 20 (instead of the default 30), and it seems that stateTimeoutSecond is discarded :

```
zkDetectionTimeout = 20
refreshSeconds = 20
stateTimeoutSecond = "30"
```

From the template : 
```
stateTimeoutSecond = "{{getv "/mesos/timeout" "30"}}"
```

`/mesos/timeout` does not seem to be defined in config.toml, "30" should be 30 (no quotes)

**Comment by deric** [comment]
Which version of the package are you using?

**Comment by deric** [comment]
Should be fixed in next DC/OS Traefik release. Until it'is merged you can update bootstrap URI.
