### ISSUE TITLE
is there any examples to use traefik as load balance for marathon and mesos app ?

### ISSUE THREAD

**Issue by alanhuang281** [deric/dcos-traefik#2]
is there any examples to use traefik as load balance for marathon and mesos app ?

**Comment by alanhuang281** [comment]
@deric do you have any examples that I can refer for marathon app and mesos app ? thanks very much.

**Comment by deric** [comment]
[DC/OS examples](https://github.com/dcos/examples/tree/master/traefik/1.11) includes basic Traefik usage.  For advanced Mesos configuration it's better to consult [Traefik documentation](https://docs.traefik.io/configuration/backends/mesos/).
